### ISSUE TITLE
Merge destinationOverrides if exists

### ISSUE THREAD

**Issue by zensharp** [zensharp/dpm#1]
The following package.yml may create additional `shortcuts/` within `%appdata%/Unity/Editor-5.x/Preferences/shortcuts/default`

```
include:
  - path: Layouts/*
  - path: ScriptTemplates/*
  - path: shortcuts
    destination: "%appdata%/Unity/Editor-5.x/Preferences/shortcuts/default"
```
